services:
  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=${PGUSER}
      - PG_PASSWORD=${PGPASSWORD}
      - PG_DB=${PGDATABASE}
      - PG_HOST=${PGHOST}
      - PG_PORT=${PGPORT}
