services:
  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DB=${POSTGRES_DB}
      - PG_HOST=${RAILWAY_TCP_PROXY_DOMAIN}
      - PG_PORT=${RAILWAY_TCP_PROXY_PORT}
